config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:  "tops#index"
  resources :tops, only: [:index]
  resources :records do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks

end

app/models/form/record_collection.rb
class Form::RecordCollection < Form::Base
  FORM_COUNT = 3
  attr_accessor :records, :user_id

  def initialize(attributes = {})
    super attributes
    # self.user_id = attributes[:user_id] #追加
    self.records = FORM_COUNT.times.map { Record.new() } unless self.records.present?
  end

  # records_attributesで送られてきたパラメーターをattributesという変数に代入
  def records_attributes=(attributes)
    self.records = attributes.map { |_, v| Record.new() }

    # self.records = attributes.map { |_, v| Record.new(v.merge(user_id: user_id)) }

  end

  def save
    Record.transaction do
      self.records.map(&:save!)
    end
      return true
    rescue => e
  #以下３行はログ表示
  Rails.logger.error(e.message)
  Rails.logger.error(e.backtrace.join("\n"))
  self.errors.add(:base, '保存に失敗しました')
    return false
        return false
  end


end

app/models/record.rb
class Record < ApplicationRecord
  validates :recorded_at, presence: true
  validates :spending_way_id, presence: true, numericality: { other_than: 1, message: "を選択してください。" }
  validates :spending_pay_id, presence: true, numericality: { other_than: 1, message: "を選択してください。" }
  validates :price, presence: true,numericality: { only_integer: true }


  belongs_to :user
 

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :spending_way
  belongs_to_active_hash :spending_pay


  def self.search(search)
    if search != ""
      Record.where('recorded_at LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end

end

app/models/spending_pay.rb
class SpendingPay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '現金' },
    { id: 3, name: 'カード' },
    { id: 4, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records
end

app/models/spending_way.rb
class SpendingWay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '食費' },
    { id: 3, name: '生活費' },
    { id: 4, name: '医療費' },
    { id: 5, name: '衣類' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname,presence: true
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :records
  accepts_nested_attributes_for :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    records_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_record, only: [:edit, :update, :destroy]

  def index
    @record = Record.new
    @records = Record.includes(:user).order("recorded_at DESC")
    @form = Form::RecordCollection.new

  end
  
  def new
    @record = Record.new
  end

  def create
    # 以下、1件登録用
    @record = Record.new(record_params)
    if @record.save
      redirect_to records_path
    else
      redirect_to records_path
    end
    
    # 以下、複数登録用
    # @form = Form::RecordCollection.new(record_collection_params)
  #   if @form.save
  #     redirect_to records_path
  #   else
  #     redirect_to records_path
  #   end
  end

  def show 
    # @records = Record.all

    #今月の支出状況
    # 1,データベースから今月のレコードを取得
    @spending_month = Record.where('extract(year from recorded_at) = ? AND extract(month from recorded_at) = ?', Time.now.year, Time.now.month)
    # 2,カテゴリー名でグループ化して、金額を合計する。凡例をnameに置き換える。
    @spending_way_month = @spending_month.group("spending_way_id").sum(:price).sort_by { |_, v| v }.reverse.map { |k, v| [SpendingWay.find(k).name, v] }.to_h

    #月毎の支出状況
    @selected_year = Date.new(params[:year].to_i)
    # @selected_year = params[:year] || Date.today.year
  end

  def search
    @records = Record.search(params[:recorded_at])
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to records_path
    else
      render :edit
    end
  end

  def destroy
    if @record.destroy
      redirect_to records_path
    end
  end

  private

  def record_params
    params
    .require(:record)
    .permit(:recorded_at, :spending_way_id, :spending_pay_id, :price, :description).merge(user_id: current_user.id)
  end

  # def record_collection_params
  #   params
  #   .require(:form_record_collection)
  #   .permit(records_attributes: [:recorded_at, :spending_way_id, :spending_pay_id, :price, :description, :user_id])
  #   .merge(user_id: current_user.id)
  # end

  def set_record
    @record = Record.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

def index
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# Zen Maru Gothic  font-family: 'Zen Maru Gothic', sans-serif; %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/edit.html.erb
<%= render "shared/header"%>

<div class="record-input">
    <div class="input-title">
    ▼支出を編集する
    </div>
    <%= form_with model: @record, local: true do |f| %>
    <%# <%= render 'shared/error_messages', model: f.object %>
    <div class="input-detail">
      <div class="date-content">
        <div class="input-text">
          日付
        </div>
        <%= f.date_field :recorded_at, class:"date-input", id:"record-price", placeholder:"例）3,000", size: "60" %>
      </div>
      <div class="way-content">
        <div class="input-text">
          費目
        </div>
        <%= f.collection_select(:spending_way_id,  SpendingWay.all, :id, :name, {}, {class:"select-box", id:"record-spending-way"}) %>
      </div>
      <div class="pay-content">
        <div class="input-text">
          方法
        </div>
        <%= f.collection_select(:spending_pay_id,  SpendingPay.all, :id, :name, {}, {class:"select-box", id:"record-spending-pay"}) %>
      </div>
      <div class="price-content">
        <div class="input-text">
          金額
        </div>
        <%= f.text_field :price, class:"price-input", id:"record-price", placeholder:"例）3000" %>
      </div>
      <div class="description-content">
        <div class="input-text">
          メモ
        </div>
        <%= f.text_area :description, class:"items-text", id:"record-description", placeholder:"メモ（20文字まで)", maxlength:"40" %>
      </div>
      <%# 更新ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "更新する" ,class:"sell-btn" %>
        <%= link_to 'もどる', records_path, class:'back-btn' %>
      </div>
      <%# /更新ボタン %>
    </div>
    <% end %>
  </div>

  <footer></footer>

app/views/records/index.html.erb
<body>
<% link_to '#', class:'backToTop'%>
<%= render 'shared/header'%>


<div class='maypage-header'>
  <ul class='menus'>
    <li class='menu menu1'><%= link_to '支出を1件登録', '#menu1'  %></li>
    <li class='menu menu2'><%= link_to '支出をたくさん登録', '#menu2' %></li>
    <li class='menu menu3'><%= link_to '一覧表示', '#menu3' %></li>
    <li class='menu menu4'><%= link_to '統計', record_path(@records), class:'all-report', method: :get%></li> 
  </ul>
</div>

<div class='mypage-main'>
  <div class='record-input'>
    <div class='input-title' id='menu1'>
    ▼支出を１件ずつ登録する
    </div>
    <div class='record-input-contsnts'>
      <%# <%= render 'shared/error_messages', model: f.object %>
      <div class='input-detail'>
        <%= form_with model: @record, local: true do |f| %>
        <div class='date-content'>
          <div class='input-text'>
            日付
          </div>
          <%= f.date_field :recorded_at, class:'date-input', id:'record-price', placeholder:'例）3,000', size: '60' %>
        </div>
        <div class='way-content'>
          <div class='input-text'>
            費目
          </div>
          <%= f.collection_select(:spending_way_id,  SpendingWay.all, :id, :name, {}, {class:'select-box', id:'record-spending-way'}) %>
        </div>
        <div class='pay-content'>
          <div class='input-text'>
            方法
          </div>
          <%= f.collection_select(:spending_pay_id,  SpendingPay.all, :id, :name, {}, {class:'select-box', id:'record-spending-pay'}) %>
        </div>
        <div class='price-content'>
          <div class='input-text'>
            金額
          </div>
          <%= f.text_field :price, class:'price-input', id:'record-price', placeholder:'例）3000' %>
        </div>
        <div class='description-content'>
          <div class='input-text'>
            メモ
          </div>
          <%= f.text_area :description, class:'items-text', id:'record-description', placeholder:'メモ（20文字まで)', maxlength:'40' %>
        </div>
        <div class='sell-btn-content'>
          <%= f.submit '登録する' ,class:'sell-btn', id: 'submit-save' %>
        </div>
        <% end %>
      </div>
     
      <div class='youtube'>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/c6DuvLPzjrg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
    </div>  
  </div>

  <div class='record-multi-input'>
    <div class='input-title' id='menu2' >
      ▼一度にたくさん保存する（実装中）
    </div>
    <div>
      <%= form_with model:@form, url: records_path, method: :post, local: true do |form| %>
        <table>
          <thead>
            <tr>
              <th class='table-top'>日付</th>
              <th class='table-top'>費目</th>
              <th class='table-top'>方法</th>
              <th class='table-top'>金額</th>
              <th class='table-top'>メモ</th>
            </tr> 
          </thead>
          <tbody>
            <%= form.fields_for :records do |f| %>
              <tr>
                <td><%= f.date_field :recorded_at, class:'date-input1', id:'record-price' %></td>
                <td><%= f.collection_select(:spending_way_id,  SpendingWay.all, :id, :name, {}, {class:'select-box1', id:'record-spending-way'}) %></td>
                <td><%= f.collection_select(:spending_pay_id,  SpendingPay.all, :id, :name, {}, {class:'select-box1', id:'record-spending-pay'}) %></td>
                <td><%= f.text_field :price, class:'price-input1', id:'record-price' %></td>
                <td><%= f.text_area :description, class:'items-text1', id:'record-description' %></td>
                <%= f.hidden_field :user_id, value: current_user.id %>
              </tr>
            <% end %>
          </tbody>
          </table>
          <div class='sell-btn-content1'>
          <%= form.submit '登録する' ,class:'sell-btn1', id: 'submit-save' %>
          </div>
      <% end %>
    </div>
  </div>




  <div class='report'>
    <div class='report-title'  id='menu3' >
      <div >▼</div>
      <div class='report-month'>
        <%= form_with(url: search_records_path, local: true, method: :get, class: 'search-form') do |f| %>
          <%= f.month_field :recorded_at, placeholder: '投稿を検索する', class: 'search-input' %>
          <%= f.submit '表示する', class: 'search-btn' %> （表示機能は実装中）
        <% end %>
      </div>
    </div>
    <div class='report-table'>
      <table>
        <thead>
          <tr>
            <th class='table-top'>日付</th>
            <th class='table-top'>費目</th>
            <th class='table-top'>方法</th>
            <th class='table-top'>金額</th>
            <th class='table-top'>メモ</th>
            <th class='table-top'>編集</th>
            <th class='table-top'>削除</th>
          </tr> 
        </thead>
        <tbody>
          <% @records.each do |record| %>
          <tr>
            <td class='report-date'><%= record.recorded_at.strftime('%F') %></td>
            <td class='report-spending_way'><%= record.spending_way.name %></td>
            <td class='report-spending_pay'><%= record.spending_pay.name %></td>
            <td class='report-price'><%= record.price %></td>
            <td class='report-description'><%= record.description %></td>
            <td class='report-edit'><%= link_to '編集', edit_record_path(record), method: :get, class: '#' %></td>
            <td class='report-delete'><%= link_to '削除', record_path(record) , method: :delete, class: '#', data: { confirm: '本当に削除しますか?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

<footer>
</footer>
</body>

app/views/records/search.html.erb
<%= form_with(url: search_records_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"  %> 
   <%= f.submit "検索", class: "search-btn" %> 
 <% end %> 


<h1>検索結果</h1>


  <table>
    <thead>
      <tr>
        <th class='table-top'>日付</th>
        <th class='table-top'>カテゴリ</th>
        <th class='table-top'>方法</th>
        <th class='table-top'>金額</th>
        <th class='table-top'>メモ</th>
        <th class='table-top'>編集</th>
        <th class='table-top'>削除</th>
      </tr> 
    </thead>
    <tbody>
      <% @records.each do |record| %>
      <tr>
        <td class='report-date'><%= record.recorded_at.strftime('%F') %></td>
        <td class='report-spending_way'><%= record.spending_way.name %></td>
        <td class='report-spending_pay'><%= record.spending_pay.name %></td>
        <td class='report-price'><%= record.price %></td>
        <td class='report-description'><%= record.description %></td>
        <td class='report-edit'><%= link_to '編集', edit_record_path(record), method: :get, class: "#" %></td>
        <td class='report-delete'><%= link_to '削除', record_path(record) , method: :delete, class: "#", data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/records/show.html.erb
<%= render "shared/second_header" %>
<h2>（実装中）<h2>

<div class="report">
  <%= form_with(url: search_records_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.month_field :recorded_at, class: "search-input" %>
  <%= f.submit "表示", class: "search-btn" %>
<% end %> 
</div>

<h2>▼今月の支出状況</h2>
<%= @spending_way_month  %>
<%= pie_chart @spending_way_month,width:'500px' %>

<h2>▼月毎の支出状況(費目ごと)</h2>

<%= form_with(model:@record, method: :get,remote: true) do |f| %>
  <%= f.select :year, options_for_select((2021..Date.today.year).to_a.reverse, params[:year]), prompt: '年を選択してください' %>
  <%= f.submit '検索' %>
<% end %>


<%# <% SpendingWay.where.not(id: 1).each do |spending_way| %>
  <%# <div id="<%= spending_way.name.parameterize-chart"> %> 
    <%# <% data = spending_way.records.where(recorded_at: @selected_year.beginning_of_year..@selected_year.end_of_year).group_by_month(:recorded_at, format: "%Y年%m月").sum(:price) %>
    <%# <% next if data.values.all?(&:zero?) %> 
    <%# <%= line_chart data, width: '500px', title: spending_way.name %> 
  <%# </div> %>
<%# <% end %> 


<%# <% SpendingWay.where.not(id: 1).each do |spending_way| %> 
  <%# <% data = spending_way.records.where(recorded_at: @selected_year.beginning_of_year..@selected_year.end_of_year).group_by_month(:recorded_at, format: "%Y年%m月").sum(:price) %>
  <%# <% next if data.values.all?(&:zero?) %> 
  <%# <%= line_chart data, width: '500px', title: spending_way.name %> 
<%# <% end %> 


<% SpendingWay.where.not(id: 1).each do |spending_way| %>
  <% data = spending_way.records.group_by_month(:recorded_at, format: "%Y年%m月").sum(:price) %>
  <% next if data.values.all?(&:zero?) %>
  <%= line_chart data, width: '500px', title: spending_way.name %>
<% end %>


<h2>▼月毎の支出合計の遷移</h2>
<%= line_chart Record.group_by_month(:recorded_at, format: "%Y年%m月").sum(:price),legend:'月毎の支出合計', width:'500px' %>


<footer>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='record-page-header'>
  <div class='header-logos'>
    <div class='header-left'>
      <p class='greeting'>
        こんにちは!&nbsp;
        <%= current_user.nickname %>
        さん  マイページへようこそ!
      </p>
    </div>
    <div>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'logout' %>
    </div>
  </div>
</header>

app/views/shared/_second_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='record-page-header'>
  <div class='header-logos'>
    <div class='header-left'>
      <h1>マイページ</h1>
      <h2 class='greeting'>
        こんにちは!
        <%= current_user.nickname %>
        さん
      </h2>
</div>
    <%= link_to 'マイページトップへ戻る', records_path, class: 'move-mypage-top' %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'logout' %>
  </div>
</header>

app/views/tops/index.html.erb
<div class='top-page'>
  <div class='top-main-contents'>
      <div class='top-main-contents-logos'>
       <p id='title'><span>家</span>
       <span>計</span>
       <span>簿</span><br>
       <span>ア</span>
       <span>プ</span>
       <span>リ</span></p>
      </div>
      <div class='top-main-contents-button'>
        <ul class='button-lists'>
        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.nickname}さん", records_path, class: 'user-nickname',id:'top-btn' %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'top-logout',id:'top-btn' %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class:'top-log-in', method: :get, id:'top-btn' %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class:'top-sign-up',method: :get, id:'top-btn' %></li>
        <% end %>
        </ul>
      </div>
  </div>
</div>